# Generated by Django 4.2.7 on 2025-04-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortmanager',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
