# Generated by Django 4.2.7 on 2025-04-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
