# Generated by Django 4.2.7 on 2025-04-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0005_remove_booking_created_at_booking_payment_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomAvailability',
        ),
    ]
