# Generated by Django 4.2.7 on 2025-04-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0008_bookroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='available_rooms',
            field=models.JSONField(default=dict),
        ),
    ]
