# Generated by Django 4.2.7 on 2025-04-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0011_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resortmanager',
            name='address',
            field=models.CharField(choices=[('Đà Nẵng', 'Đà Nẵng'), ('Hà Nội', 'Hà Nội'), ('HCM', 'TP Hồ Chí Minh')], max_length=50),
        ),
    ]
