# Generated by Django 4.2.7 on 2025-04-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0013_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='room_type_capacity',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
