# Generated by Django 4.2.7 on 2025-04-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0015_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
