# Generated by Django 5.2 on 2025-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0017_resortmanagerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_income_generated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_rooms_booked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
