# Generated by Django 5.2 on 2025-04-20 14:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0018_booking_total_income_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_income_generated',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_rooms_booked',
        ),
        migrations.AddField(
            model_name='bookroom',
            name='total_income_generated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bookroom',
            name='total_rooms_booked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
