# Generated by Django 5.2 on 2025-04-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0020_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
