# Generated by Django 5.2 on 2025-04-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0021_message_image_alter_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='image',
            new_name='chat_image',
        ),
    ]
