# Generated by Django 5.2 on 2025-04-20 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0022_rename_image_message_chat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_image',
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_chat', models.ImageField(upload_to='chat_images/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appbook.message')),
            ],
        ),
    ]
