# Generated by Django 4.2.7 on 2025-04-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0023_remove_message_chat_image_messageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
