# Generated by Django 5.2 on 2025-05-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0025_resort_liked_users_userlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortmanager',
            name='momo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resortmanager',
            name='momo_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='UserLike',
        ),
    ]
