# Generated by Django 5.2 on 2025-05-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0028_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qr_app', models.ImageField(blank=True, null=True, upload_to='qr_app/')),
            ],
        ),
    ]
